"""empty message

Revision ID: 5b6b9b04a677
Revises: aa97e5537171
Create Date: 2023-08-02 13:56:27.169194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b6b9b04a677'
down_revision = 'aa97e5537171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cobranzas', sa.Column('user_confirm', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cobranzas', 'user_confirm')
    # ### end Alembic commands ###
