"""empty message

Revision ID: 7ec92e55d055
Revises: 94ebd0df7508
Create Date: 2023-08-20 22:37:05.397915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ec92e55d055'
down_revision = '94ebd0df7508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tipo', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tipo')
    # ### end Alembic commands ###
