"""empty message

Revision ID: 94ebd0df7508
Revises: 0a6f176861da
Create Date: 2023-08-20 22:25:26.122602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ebd0df7508'
down_revision = '0a6f176861da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('email', 'users', ['email'], unique=False)
    # ### end Alembic commands ###
